package it.noi.edisplay.model;

public enum ImageFieldType {
    CUSTOM_TEXT,
    LOCATION_NAME,
    EVENT_DESCRIPTION,
    EVENT_START_DATE,
    EVENT_END_DATE,
    UPCOMING_EVENT_DESCRIPTION,
    UPCOMING_EVENT_START_DATE,
    UPCOMING_EVENT_END_DATE
}
